#nvidia-addon
[Config]
Dependencies=base
ImageId=ext-nvidia-addon

[Output]
Format=addon
Output=ext-nvidia-addon-%a_%v
OutputExtension=addon.efi
CompressOutput=zstd

[Content]
KernelCommandLine=nvidia-drm.modeset=1 module_blacklist=nouveau
BaseTrees=%O/base_%v