#nvidia-runtime
[Config]
Dependencies=os

[Match]
Distribution=ubuntu
Release=resolute
Profiles=sysexts

[Output]
Format=sysext
Overlay=yes
Output=nvidia-runtime-%a_%v
ImageId=nvidia-runtime
ImageVersion=%v
OutputExtension=raw
CompressOutput=xz

[Content]
Bootable=no
BaseTrees=%O/Elementary_%v_%a.raw
Environment=DEB_BUILD_PROFILES=nokerneldkms
RemovePackages=linux-modules-nvidia-580-open-generic
Packages=
    libnvidia-gl-580
    nvidia-utils-580
    nvidia-driver-580-open