[Config]
MinimumVersion=26~devel
Dependencies=
    base
	sysupdate
    liveiso

[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=main,universe

[Build]
ToolsTree=default
CacheDirectory=mkosi.cache
ToolsTreePackages=grub-efi-amd64-bin
Incremental=yes
ToolsTreeDistribution=ubuntu
ToolsTreeRelease=resolute

[Output]
OutputDirectory=mkosi.output/
Format=none
