[Config]
Dependencies=os

[Match]
Distribution=ubuntu
Release=resolute
Profiles=sysupdate

[Output]
Format=sysext
Overlay=yes
ImageId=cowsay

[Content]
Bootable=no
BaseTrees=%O/Elementary_%v_%a.raw
Packages=
    cowsay
    