[UKIProfile]
Profile=
        ID=emergency
        TITLE=Boot into Emergency Mode

Cmdline=
        root=dissect
        mount.usr=dissect
        systemd.unit=emergency.target
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:swap=encrypted+unused+absent:home=unprotected+absent:=ignore
        systemd.image_filter=usr=Elementary_*:usr-verity=Elementary_*:usr-verity-sig=Elementary_*:root=Elementary-*:swap=Elementary-*:home=Elementary-*
        ipe.enforce=0

SignExpectedPcr=yes
