[Match]
Distribution=ubuntu

[Content]
Packages=systemd-container
Bootable=no
UnifiedKernelImageFormat=%i_%v

VolatilePackages=
    passwd
    login
    uidmap
    systemd-boot

InitrdPackages=
    linux-firmware
    cryptsetup
    cryptsetup-bin
    systemd-container