[Match]
Profiles=classic
Distribution=ubuntu

[Output]
SplitArtifacts=partitions
Format=disk
OutputDirectory=../../mkosi.output/classic
ImageId=Elementary

[Content]
Bootable=yes
Bootloader=grub
UnifiedKernelImageFormat=%i_%v
InitrdProfiles=
KernelInitrdModules=
    default
    ahci
    nvme
    xhci_pci
    usb_storage
    uas
    sd_mod
KernelCommandLine=
    splash
    quiet
    rw
    audit=0
    ipe.enforce=0
Packages=
    grub-efi-amd64-bin

[Validation]
SecureBoot=no
SignExpectedPcr=no
