#nvidia-addon
[Match]
Distribution=ubuntu
Release=resolute
Profiles=sysexts

[Output]
Format=addon
Output=elementary-nvidia-%a_%v
OutputExtension=addon.efi
CompressOutput=xz

[Content]
KernelCommandLine=nvidia-drm.modeset=1 module_blacklist=nouveau
BaseTrees=%O/Elementary_%v_%a.raw
Packages=systemd-boot-efi