#!/bin/bash
set -eo pipefail

echo "Thank you for testing! <3"

apt-get install fzf systemd-repart systemd-boot -y

medium=$(findmnt -rn -t iso9660,udf -o TARGET | head -1)
extra="$medium/extra"
raw_src=$(find "$extra" -maxdepth 1 -type f -name '*.raw' | head -n1)
efi_src=$(find "$extra" -maxdepth 1 -type f -name '*.efi' | head -n1)
repart_src="$extra/repart.d"

echo "Using source image: $raw_src"

selected_disk=$(lsblk -d -n -p -o NAME,SIZE,MODEL -e 7,11 | fzf \
    --prompt="Select installation disk (ALL DATA WILL BE LOST): " \
    --header="NAME          SIZE  MODEL")

if [ -z "$selected_disk" ]; then
    echo "Installation aborted: No disk selected."
    exit 1
fi

dest_dev=$(echo "$selected_disk" | awk '{print $1}')

echo "$dest_dev selected for repartitioning..."
echo "Destroying drive in 3s ..."
sleep 1
echo "Destroying drive in 2s ..."
sleep 1
echo "Destroying drive in 1s ..."
sleep 1

/usr/sbin/wipefs -a "$dest_dev"

systemd-repart \
    --copy-from="$raw_src" \
    --definitions="$repart_src" \
    --dry-run=no \
    --empty=force \
    "$dest_dev"

echo "Everything is done! Enjoy your stay."