[Match]
Profiles=sysupdate
Distribution=ubuntu

[Output]
SplitArtifacts=uki,partitions
Format=disk
OutputDirectory=../../mkosi.output/sysupdate
ImageId=Elementary

[Content]
Bootable=yes
Bootloader=systemd-boot
InitrdProfiles=
KernelInitrdModules=
    default
    ahci
    nvme
    xhci_pci
    usb_storage
    uas
    sd_mod
    dm-verity
KernelCommandLine=
    splash
    quiet
    root=dissect
    mount.usr=dissect
    rw
    audit=0
    systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=unprotected+absent:home=unprotected+absent:=ignore
    systemd.image_filter=usr=Elementary_*:usr-verity=Elementary_*:usr-verity-sig=Elementary_*:root=Elementary-*:home=Elementary-*
    ipe.enforce=0

[Validation]
SecureBoot=no
SignExpectedPcr=no
