[Content]
RemoveFiles=
    /usr/bin/chsh
    /usr/bin/lchsh

VolatilePackages=
    systemd-container

Packages=
    btrfs-progs
    cryptsetup
    dbus-user-session
    flatpak
    fzf
    glycin-loaders
    gnome-disk-utility
    gnome-keyring
    iputils-ping
    libpam-gnome-keyring
    libpam-systemd
    lightdm
    linux-firmware
    linux-image-generic
    locales-all
    lvm2
    micro
    ncurses-base
    network-manager
    pipewire-audio
    plymouth
    plymouth-theme-elementary
    sudo-rs
    systemd-boot
    systemd-cryptsetup
    systemd-homed
    systemd-repart
    systemd-resolved
    systemd-zram-generator
    ubuntu-keyring
    vim
    x11-common
    xdg-desktop-portal-gtk
    xdg-user-dirs
    xz-utils
    zstd