[Content]
RemoveFiles=
    /usr/bin/chsh
    /usr/bin/lchsh

VolatilePackages=
    systemd-container

RemovePackages=
    anacron

Packages=
    plymouth
    plymouth-theme-elementary
    linux-image-generic
    linux-firmware
    libpam-systemd
    dbus-user-session
    systemd-resolved
    systemd-cryptsetup
    cryptsetup
    btrfs-progs
    bolt
    x11-common
    curl
    wget
    binutils
    iputils-ping
    ubuntu-keyring
    distrobox
    fastfetch
    oras
    flatpak
    htop
    podman
    vim
    fzf
    gcr
    git
    locales-all
    glycin-loaders
    gnome-disk-utility
    gnome-keyring
    libpam-gnome-keyring
    totem-video-thumbnailer
    just
    lshw
    nano
    ncurses-base
    network-manager
    ssh-askpass-gnome
    systemd-homed
    sudo-rs
    yq
    jq
    xdg-desktop-portal-gtk
    xdg-user-dirs