[Match]
Distribution=ubuntu

[Content]
Packages=
    contractor
    io.elementary.appcenter
    io.elementary.bluetooth-daemon
    io.elementary.code
    io.elementary.feedback
    io.elementary.mail
    io.elementary.monitor
    io.elementary.onboarding
    io.elementary.sideload
    io.elementary.tasks
    io.elementary.terminal
    pantheon-files
    pantheon-photos





