[Match]
Distribution=ubuntu

[Content]
WithRecommends=yes
Packages=
    elementary-desktop
    elementary-minimal
    elementary-standard
    pantheon-greeter # if not explicitly named, get stuck on a black screen post-install
    gala # if not explicitly named, get stuck on a black screen post-install