#Prop
[Config]
Dependencies=base
ImageId=ext-proprietary

[Output]
Format=sysext
Overlay=yes
Output=ext-proprietary-%a_%v
CompressOutput=zstd

[Validation]
Verity=no

[Content]
Bootable=no
BaseTrees=%O/base_%v
Packages=
    bcmwl-kernel-source
    broadcom-sta-dkms
FinalizeScripts=depmod-prop