[Config]
Dependencies=base

[Output]
Format=sysext
Overlay=yes
ImageId=ext-devel

[Validation]
Verity=no
CompressOutput=zstd

[Content]
Bootable=no
BaseTrees=%O/base_%v
Packages=
    binutils
    build-essential
    cmake
    docker.io
    docker-compose
    flatpak-builder
    fzf
    gcc
    gettext
    jq
    just
    lshw
    meson
    podman-compose
    sassc
    wget
    yq