#nvidia-modules
[Config]
Dependencies=os

[Match]
Distribution=ubuntu
Release=resolute
Profiles=sysexts

[Output]
Format=sysext
Overlay=yes
Output=nvidia-modules-%a_%v
ImageId=nvidia-modules
ImageVersion=%v
OutputExtension=raw
CompressOutput=xz

[Content]
Bootable=no
BaseTrees=%O/Elementary_%v_%a.raw
Environment=DEB_BUILD_PROFILES=nokerneldkms
Packages=linux-modules-nvidia-580-open-generic