[Match]
Profiles=flash

[Output]
Format=directory
ElTorito=yes
SplitArtifacts=kernel,initrd
OutputDirectory=../../mkosi.output/live
ImageId=ElementaryLive

[Content]
Bootable=yes
Packages=
    gparted
    grub-efi-amd64
    grub-pc-bin
    casper
    initramfs-tools
Bootloader=grub
KernelInitrdModules=
    default
    ahci
    nvme
    xhci_pci
    usb_storage
    uas
    sd_mod
    sr_mod
    isofs
    loop
    ext4
KernelCommandLine=
    rw
    console=ttyS0
    boot=casper

[Validation]
SecureBoot=no
SignExpectedPcr=no