name: Monthly Image-based OS 9

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-26.04
            arch: amd64
          - runner: ubuntu-26.04-arm
            arch: arm64
    runs-on: ${{ matrix.runner }}

    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
    - name: Clone build scripts
      uses: actions/checkout@v7
    - name: Install mkosi
      run: sudo apt-get update && sudo apt-get install -y mkosi
    - name: Build
      run: sudo mkosi -B --debug --force --profile=sysupdate
    - name: Upload
      run: |
        ./upload.sh "${{ secrets.key }}" "${{ secrets.secret }}" "${{ secrets.endpoint }}" "${{ secrets.bucket }}" "${{ secrets.install_bucket }}"
