name: Monthly Image-based OS 9

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch: {}

jobs:
  build:
    environment: elementary
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-26.04
            arch: amd64
          - runner: ubuntu-26.04-arm
            arch: arm64
    runs-on: ${{ matrix.runner }}

    container:
      image: ubuntu:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
    - name: Clone build scripts
      uses: actions/checkout@v7

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y mkosi

    - name: Build
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: Upload
      run: |
        ./upload.sh "${{ secrets.KEY }}" "${{ secrets.SECRET }}" "${{ secrets.ENDPOINT }}" "${{ secrets.INSTALLER_BUCKET }}" "${{ secrets.UPDATES_BUCKET }}"
