name: Build and Release (elementary OS 9)

on:
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build Image and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v8

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install just podman -y

      - name: Generate key
        run: just genkey

      - name: Release
        run: just do-release

      - name: Fix output dir ownership
        run: |
          sudo chown -R "$(id -u):$(id -g)" mkosi.output
          sudo chmod -R u+rwX mkosi.output

      - name: Compress (xz7) usr.raw
        run: |
          find mkosi.output/sysupdate -maxdepth 1 -type f -name "*.usr-x86-64.raw" -exec xz -5v -T0 {} +

      - name: Sign ISO
        run: |
          cd mkosi.output
          sha256sum elementary-liveiso.iso > elementary-liveiso.iso.sha256

      - name: Generate SHA256SUMS (all partitions)
        run: |
          cd mkosi.output
          sha256sum sysupdate/*.efi sysupdate/*.usr-*.raw.xz sysupdate/*.usr-*-verity*.raw sysupdate/*.usr-*-verity-sig*.raw \
            | sed 's|sysupdate/||' > SHA256SUMS
          cat SHA256SUMS

      - name: Extract Date
        id: get_date
        run: |
          FILE_PATH=$(ls mkosi.output/sysupdate/elementary_*.raw | grep -E 'elementary_[0-9]+\.raw$' | head -n 1)
          TIMESTAMP=$(basename "$FILE_PATH" | sed 's/^elementary_//;s/\..*//')
          echo "RELEASE_TAG=os9-$TIMESTAMP" >> "$GITHUB_OUTPUT"

      - name: Upload usr, iso and SHA256SUMS to Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.secret }}
          AWS_DEFAULT_REGION: auto
        run: |
          cd mkosi.output
          for f in sysupdate/*.usr-*.raw.xz sysupdate/*.usr-*.raw.xz.sha256 \
                   elementary-liveiso.iso elementary-liveiso.iso.sha256 SHA256SUMS; do
            aws s3 cp "$f" "s3://${{ secrets.bucket }}/" \
              --endpoint-url "${{ secrets.endpoint }}"
          done


      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.get_date.outputs.RELEASE_TAG }}
          name: Release ${{ steps.get_date.outputs.RELEASE_TAG }}
          files: |
            mkosi.output/sysupdate/*.efi
            mkosi.output/sysupdate/*.usr-*-verity*.raw
            mkosi.output/sysupdate/*.usr-*-verity-sig*.raw
            mkosi.output/sysupdate/SHA256SUMS